## Closed world

### 1. RandomForest

In [1]:
from google.colab import drive
import pickle
import numpy as np

In [2]:
drive.mount('/content/drive', force_remount=True)

Mounted at /content/drive


In [3]:
# 데이터 로드

with open("./drive/MyDrive/data/processed_mon_data_closed_world.pkl", "rb") as f:
    data = pickle.load(f)
X = np.column_stack(list(data['features'].values()))
y = np.array(data['y'])  # 라벨은 그대로 사용

In [4]:
# 데이터 분할

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, stratify=y, random_state=42)

In [5]:
# 모델 학습 - Random Forest

from sklearn.ensemble import RandomForestClassifier
model_rf = RandomForestClassifier(max_depth=20, n_estimators=100, random_state=42, class_weight='balanced')
model_rf.fit(X_train, y_train)


RandomForestClassifier(class_weight='balanced', max_depth=20, random_state=42)

In [6]:
# 모델 평가

from sklearn.metrics import classification_report, accuracy_score, precision_score, recall_score, f1_score, confusion_matrix
y_pred = model_rf.predict(X_test)
accuracy = accuracy_score(y_test, y_pred)
precision = precision_score(y_test, y_pred, average='weighted')
recall = recall_score(y_test, y_pred, average='weighted')
print(f"Accuracy: {accuracy:.2f}")
print(f"Precision: {precision:.2f}")
print(f"Recall: {recall:.2f}")
print(classification_report(y_test, y_pred))


Accuracy: 0.64
Precision: 0.64
Recall: 0.64
              precision    recall  f1-score   support

           0       0.58      0.45      0.51        40
           1       0.47      0.40      0.43        40
           2       0.69      0.88      0.77        40
           3       0.62      0.70      0.66        40
           4       0.57      0.60      0.59        40
           5       0.72      0.57      0.64        40
           6       0.83      0.75      0.79        40
           7       0.69      0.72      0.71        40
           8       0.68      0.75      0.71        40
           9       0.61      0.62      0.62        40
          10       0.65      0.50      0.56        40
          11       0.61      0.50      0.55        40
          12       0.86      0.80      0.83        40
          13       0.56      0.45      0.50        40
          14       0.54      0.47      0.51        40
          15       0.72      0.78      0.75        40
          16       0.75      0.53    

### 2. Support Vector Machine

In [ ]:
# 모델 학습 - SVM

from sklearn.svm import SVC
model_svm = SVC(kernel='rbf', C=200, gamma=0.5, random_state=42, class_weight='balanced')
model_svm.fit(X_train, y_train)


SVC(C=200, class_weight='balanced', gamma=0.5, random_state=42)

In [8]:
# 모델 평가

y_pred = model_svm.predict(X_test)

accuracy = accuracy_score(y_test, y_pred)
precision = precision_score(y_test, y_pred, average='weighted')
recall = recall_score(y_test, y_pred, average='weighted')
conf_matrix = confusion_matrix(y_test, y_pred)

print(f"Accuracy: {accuracy:.2f}")
print(f"Precision: {precision:.2f}")
print(f"Recall: {recall:.2f}")
print(f"Confusion Matrix:")
print(conf_matrix)

print(classification_report(y_test, y_pred))

Accuracy: 0.27
Precision: 0.25
Recall: 0.27
Confusion Matrix:
[[ 1  0  1 ...  0  2  6]
 [ 0  0  3 ...  0  0  0]
 [ 0  0 21 ...  0  2  0]
 ...
 [ 0  0  2 ...  0  0  5]
 [ 0  0  0 ...  0 32  0]
 [ 0  0  0 ...  0  0 14]]
              precision    recall  f1-score   support

           0       0.50      0.03      0.05        40
           1       0.00      0.00      0.00        40
           2       0.19      0.53      0.27        40
           3       0.67      0.35      0.46        40
           4       0.27      0.07      0.12        40
           5       0.11      0.07      0.09        40
           6       0.19      0.35      0.25        40
           7       0.25      0.20      0.22        40
           8       0.60      0.07      0.13        40
           9       0.29      0.23      0.25        40
          10       0.09      0.03      0.04        40
          11       0.15      0.35      0.21        40
          12       0.57      0.60      0.59        40
          13       0.00  

/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/m